const mentors = [
    {firstName: "Nathaniel",
     lastName: "Driggs",
     userName: "ndriggs",
     subjects: ["Mathematics",
		"Chinese",
		"Korean",
		"Economics",
		"Science",
		"Computer Science"],
     times: [{start: "17:00", end: "19:00", day: "Monday"},
	     {start: "17:00", end: "19:00", day: "Tuesday"},
	     {start: "17:00", end: "19:00", day: "Wednesday"},
	     {start: "17:00", end: "19:00", day: "Thursday"},
	     {start: "05:00", end: "22:00", day: "Saturday"}]},
    {firstName: "Blaine",
     lastName: "Blood",
     userName: "bblooood3",
     subjects: ["Business",
		"Law",
		"Writing"],
     times: [{start: "17:00", end: "22:00", day: "Tuesday"},
	     {start: "17:00", end: "22:00", day: "Wednesday"},
	     {start: "05:00", end: "18:30", day: "Thursday"}]},
    {firstName: "Kristen",
     lastName: "Ellis",
     userName: "kellis55",
     subjects: ["Cooking",
		"Reading",
		"Driving"],
     times: [{start: "10:00", end: "15:00", day: "Monday"},
	     {start: "10:00", end: "15:00", day: "Tuesday"},
	     {start: "10:00", end: "15:00", day: "Wednesday"},
	     {start: "10:00", end: "15:00", day: "Thursday"},
	     {start: "10:00", end: "15:00", day: "Friday"}]},
    {firstName: "Richard",
     lastName: "Burnside",
     userName: "rburner8",
     subjects: ["Engineering",
		"Finance",
		"Investing"],
     times: [{start: "19:00", end: "22:00", day: "Monday"},
	     {start: "19:00", end: "22:00", day: "Tuesday"},
	     {start: "19:00", end: "22:00", day: "Wednesday"},
	     {start: "19:00", end: "22:00", day: "Thursday"},
	     {start: "19:00", end: "22:00", day: "Friday"},
	     {start: "05:00", end: "22:00", day: "Saturday"},
	     {start: "05:00", end: "22:00", day: "Sunday"}]},
    {firstName: "Karen",
     lastName: "Burnside",
     userName: "kb3",
     subjects: ["Business",
		"Finance",
		"Accounting"],
     times: [{start: "10:00", end: "14:00", day: "Monday"},
	     {start: "10:00", end: "14:00", day: "Tuesday"},
	     {start: "10:00", end: "14:00", day: "Wednesday"},
	     {start: "10:00", end: "14:00", day: "Thursday"},
	     {start: "10:00", end: "14:00", day: "Friday"},
	     {start: "10:00", end: "14:00", day: "Saturday"},
	     {start: "10:00", end: "14:00", day: "Sunday"}]},
    {firstName: "Dell",
     lastName: "Mcumber",
     userName: "delly49",
     subjects: ["Cardiology"],
     times: [{start: "08:00", end: "17:00", day: "Monday"},
	     {start: "08:00", end: "17:00", day: "Tuesday"},
	     {start: "08:00", end: "17:00", day: "Wednesday"},
	     {start: "08:00", end: "17:00", day: "Thursday"},
	     {start: "08:00", end: "17:00", day: "Friday"},
	     {start: "08:00", end: "17:00", day: "Saturday"},
	     {start: "08:00", end: "17:00", day: "Sunday"}]},
    {firstName: "Austin",
     lastName: "Rodenberg",
     userName: "aroden",
     subjects: ["Dental"],
     times: [{start: "09:00", end: "17:00", day: "Monday"},
	     {start: "09:00", end: "17:00", day: "Tuesday"},
	     {start: "09:00", end: "17:00", day: "Wednesday"},
	     {start: "09:00", end: "17:00", day: "Thursday"},
	     {start: "09:00", end: "17:00", day: "Friday"},
	     {start: "09:00", end: "17:00", day: "Saturday"},
	     {start: "09:00", end: "17:00", day: "Sunday"}]},
    {firstName: "Alvaro",
     lastName: "Galvez",
     userName: "alvo30",
     subjects: ["Human Resources",
	       "Administration"],
     times: [{start: "18:00", end: "22:00", day: "Monday"},
	     {start: "18:00", end: "22:00", day: "Tuesday"},
	     {start: "18:00", end: "22:00", day: "Wednesday"},
	     {start: "18:00", end: "22:00", day: "Thursday"},
	     {start: "18:00", end: "22:00", day: "Friday"}]},
    {firstName: "McKayla",
     lastName: "Bowen",
     userName: "mcbow3",
     subjects: ["Family Life",
	       "Music"],
     times: [{start: "14:00", end: "22:00", day: "Tuesday"},
	     {start: "14:00", end: "22:00", day: "Thursday"}]},
    {firstName: "Lydia",
     lastName: "Dahlke",
     userName: "ldahl",
     subjects: ["Administration",
	       "Science"],
     times: [{start: "15:00", end: "22:00", day: "Thursday"}]},
    {firstName: "Tyler",
     lastName: "Savage",
     userName: "savage123",
     subjects: ["Computer Science",
		"Music"],
     times: [{start: "10:00", end: "13:00", day: "Monday"},
	     {start: "10:00", end: "13:00", day: "Wednesday"},
	     {start: "10:00", end: "13:00", day: "Thursday"},
	     {start: "10:00", end: "13:00", day: "Friday"}]},
    {firstName: "Chris",
     lastName: "Rains",
     userName: "crains4",
     subjects: ["Psychology"],
     times: [{start: "13:00", end: "16:00", day: "Monday"},
	     {start: "13:00", end: "16:00", day: "Tuesday"},
	     {start: "13:00", end: "16:00", day: "Wednesday"},
	     {start: "13:00", end: "16:00", day: "Thursday"},
	     {start: "13:00", end: "16:00", day: "Friday"}]},
    {firstName: "Blake",
     lastName: "De Buck",
     userName: "bdbuck",
     subjects: ["Writing",
	       "Reading"],
     times: [{start: "14:00", end: "18:00", day: "Tuesday"}]}
]

module.exports = mentors;
