const subjects = [
    {name: "Accounting"},
		  {name: "Acting"},
		  {name: "Administration"},
		  {name: "Animation"},
		  {name: "Art"},
		  {name: "Biology"},
		  {name: "Business"},
		  {name: "Cardiology"},
    {name: "Chemistry"},
    {name: "Chinese"},
		  {name: "Communications"},
		  {name: "Computer Science"},
		  {name: "Cooking"},
		  {name: "Dance"},
		  {name: "Dental"},
    {name: "Driving"},
    {name: "Economics"},
		  {name: "Engineering"},
		  {name: "English"},
		  {name: "Exercise Science"},
		  {name: "Family Life"},
		  {name: "Finance"},
		  {name: "Geography"},
		  {name: "Geology"},
		  {name: "Graphic Design"},
		  {name: "History"},
		  {name: "Human Resources"},
		  {name: "Information Systems"},
		  {name: "Information Technology"},
    {name: "Investing"},
    {name: "Korean"},
		  {name: "Law"},
		  {name: "Linguistics"},
		  {name: "Mathematics"},
		  {name: "Music"},
		  {name: "Neuroscience"},
		  {name: "Nutrition"},
		  {name: "Philosophy"},
		  {name: "Physics"},
		  {name: "Psychology"},
    {name: "Reading"},
    {name: "Science"},
		  {name: "Social Studies"},
		  {name: "Statistics"},
		  {name: "Theatre"},
		  {name: "Wildlife"},
		  {name: "Writing"},
];

module.exports = subjects;
